name: HunterxHunter UHC
version: 0.1
author: Aksyo
main: net.hunter.main.Main
commands:
  roleconfig:
    permission: hunter.config.map
    aliases: hrc
  mapconfig:
    permission: hunter.config.map
    aliases: hmc